/**:
    ros__parameters:
      video_device: "/dev/camera_tilted_down"
      frame_id: "camera_tilted_down_optical_frame"

      # Unfortunately the usb cam node doesn't properly support efficiently converting
      # most of its suppported pixel_formats to ros messages so most options don't help
      # pixel_format: "raw_mjpeg" # raw_mjpeg seems to be like 3x more cpu efficient than "mjpeg2rgb"
      pixel_format: "mjpeg2rgb"
      camera_name: "camera_tilted_down"
      image_height: 480
      image_width: 640
      fps: 30
      camera_info_url: "package://pontus_sensors/config/calibration/tilted_camera_calibration.yaml"

      image_raw:
        enable_pub_plugins: [
          'image_transport/compressed'
        ]