microstrain_inertial_driver:
  ros__parameters:
    # port: /dev/serial/by-id/usb-MicroStrain__Inc._3DM-GX3-25_Orientation_Sensor_6223.12899______-if00
    #port: /dev/serial/by-id/usb-MicroStrain__Inc._3DM-GX3-25_Orientation_Sensor_6223.12892______-if00
    port: /dev/serial/by-id/usb-MicroStrain__Inc._3DM-GX3-45_Orientation_Sensor_6228.01429______-if00    
    use_enu_frame: True
    #imu_frame_id: imu_frame
    #device_setup: True
    #debug: True
    #diagnostics: True
    #publish_filter: True
    #filter_auto_init: True
    #filter_reset_after_config: True
    # poll_port: True
    #filter_sensor2vehicle_frame_selector: 0
    #name: 'gx3'
    imu_linear_cov: [0.2, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
    imu_orientation_cov: [0.2, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.2]
    #filter_use_compensated_accel: False 
