std_msgs/Header header

# ------ Object Type Groupings ------
pontus_msgs/SemanticObject[] gate_image_shark
pontus_msgs/SemanticObject[] gate_image_fish
pontus_msgs/SemanticObject[] gate_left
pontus_msgs/SemanticObject[] gate_right
pontus_msgs/SemanticObject[] slalom_red
pontus_msgs/SemanticObject[] slalom_white
pontus_msgs/SemanticObject[] vertical_marker
pontus_msgs/SemanticObject[] bin
pontus_msgs/SemanticObject[] octagon
pontus_msgs/SemanticObject[] target


# ------ Meta Objects ------

pontus_msgs/SemanticMetaGate meta_gate