# Odometry (Only used for testing)
- ros_topic_name: "/dvl/odometry"
  gz_topic_name: "/model/pontus/odometry_with_covariance"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.OdometryWithCovariance"
  direction: GZ_TO_ROS

- ros_topic_name: "/pontus/depth_0"
  gz_topic_name: "/model/pontus/odometry_with_covariance"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.OdometryWithCovariance"
  direction: GZ_TO_ROS
