name: ROS Jazzy
on:
  pull_request_target:
    types: [opened, reopened, edited]
    paths-ignore:
      - '.github/**'
      - '**.md'
  workflow_dispatch:

jobs:
  humble:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:jazzy-desktop
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget python3-vcstool python3-colcon-coveragepy-result
      - name: Build and test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: jazzy
          skip-tests: true
          import-token: ${{ secrets.GITHUB_TOKEN }}
          rosdep-check: true
